/***
 * 全局枚举
 */

/***
 * 地图瓦片枚举
 */
export enum TILE_TYPE_ENUM {
  WALL_ROW = 'WALL_ROW',
  WALL_COLUMN = 'WALL_COLUMN',
  WALL_LEFT_TOP = 'WALL_LEFT_TOP',
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
  CLIFF_LEFT = 'CLIFF_ROW_START',
  CLIFF_CENTER = 'CLIFF_ROW_CENTER',
  CLIFF_RIGHT = 'CLIFF_ROW_END',
  FLOOR = 'FLOOR',
}
/***
 * 事件类型枚举
 */
export enum EVENT_ENUM {
  PLAYER_CTRL = 'PLAYER_CTRL',
  PLAYER_MOVE_END = 'PLAYER_MOVE_END',
  ATTACK_ENEMY = 'ATTACK_ENEMY',
  ATTACK_PLAYER = 'ATTACK_PLAYER',
  RECORD_STEP = 'RECORD_STEP',
  REVOKE_STEP = 'REVOKE_STEP',
  SCREEN_SHAKE = 'SCREEN_SHAKE',
  NEXT_LEVEL = 'NEXT_LEVEL',
  RESTART_LEVEL = 'RESTART_LEVEL',
  OPENDOOR = 'OPENDOOR',
  GAME_START = 'GAME_START',
  GAME_OVER = 'GAME_OVER',
  DOOR_OPEN = 'DOOR_OPEN',
  SHOW_SMOKE = 'SHOW_SMOKE',
  PLAYER_BORN = 'PLAYER_BORN',
  QUIT_BATTLE = 'QUIT_BATTLE',
}
